// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Livro } from '../livro';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Editora[] = [];
  public livros: Livro[] = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();

    this.servLivros.obterLivros().then((livros: Livro[]) => {
      this.livros = livros;
    });
  }

  excluir(codigo: string): void {
    this.servLivros.excluir(codigo).then(() => {
      return this.servLivros.obterLivros();
    }).then((livros: Livro[]) => {
      this.livros = livros;
    });
  }

  obterNome(codEditora: number): string | undefined {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main class="container mt-4">
    <h1 class="mb-4">Catálogo de Livros</h1>

    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Título</th>
                <th>Resumo</th>
                <th>Editora</th>
                <th>Autores</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros" class="py-2">
                <td class="align-middle">
                    <div>{{ livro.titulo }}</div>
                    <div>
                        <button class="btn btn-danger btn-sm mt-2" (click)="excluir(livro.codigo)">
                            Excluir
                        </button>
                    </div>
                </td>
                <td>
                    {{ livro.resumo }}
                </td>
                <td>
                    {{ livro.editora }}
                </td>
                <td>
                    {{ livro.autores }}
                </td>
            </tr>
        </tbody>
    </table>
</main>

// clientes/livros-react/src/LivroLista.js
import { useState, useEffect, useMemo } from 'react';
import { ControleLivros } from './controle/ControleLivros';
import ControleEditora from './controle/ControleEditora';

const LivroLista = () => {
    const controleLivro = useMemo(() => new ControleLivros(), []);
    const controleEditora = useMemo(() => new ControleEditora(), []);
    const [livros, setLivros] = useState([]);
    const [carregado, setCarregado] = useState(false);

    useEffect(() => {
        if (!carregado) {
            controleLivro.obterLivros().then(livrosObtidos => {
                setLivros(livrosObtidos);
                setCarregado(true);
            });
        }
    }, [carregado, controleLivro]);

    const excluir = (codigoLivro) => {
        controleLivro.excluir(codigoLivro).then(() => {
            setCarregado(false);
        });
    };

    const LinhaLivro = ({ livro }) => {
        const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);
        return (
            <tr>
                <td className="titulo-cell">
                    {livro.titulo}
                    <div>
                        <button className="excluir-button" onClick={() => excluir(livro.codigo)}>
                            Excluir
                        </button>
                    </div>
                </td>
                <td className="resumo-cell">
                    {livro.resumo}
                </td>
                <td className="editora-cell">
                    {nomeEditora}
                </td>
                <td className="autores-cell">
                    <ul>
                        {livro.autores.map((autor, index) => (
                            <li key={index}>{autor}</li>
                        ))}
                    </ul>
                </td>
            </tr>
        );
    };

    return (
        <main>
            <h1>Catálogo de Livros</h1>
            <table className="book-table">
                <thead>
                    <tr>
                        <th>Título</th>
                        <th>Resumo</th>
                        <th>Editora</th>
                        <th>Autores</th>
                    </tr>
                </thead>
                <tbody>
                    {livros.map((livro, index) => (
                        <LinhaLivro key={index} livro={livro} />
                    ))}
                </tbody>
            </table>
        </main>
    );
};

export default LivroLista;
