// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {

  public livro: Livro = new Livro();
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('');
    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista');
    });
  }
}
<main class="container mt-4">
    <h1 class="mb-4">Dados do Livro</h1>

    <form (submit)="incluir()" ngNativeValidate>
        <div class="form-group">
            <label for="titulo">Título</label>
            <input type="text" id="titulo" class="form-control" [(ngModel)]="livro.titulo" name="titulo" required />
        </div>

        <div class="form-group">
            <label for="resumo">Resumo</label>
            <textarea id="resumo" class="form-control" rows="3" [(ngModel)]="livro.resumo" name="resumo"></textarea>
        </div>

        <div class="form-group">
            <label for="editora">Editora</label>
            <select id="editora" class="form-control" [(ngModel)]="livro.editora" name="editora" required>
                <option *ngFor="let editora of editoras" [value]="editora.codEditora">
                    {{ editora.nome }}
                </option>
            </select>
        </div>


        <div class="form-group">
            <label for="autores">Autores</label>
            <textarea id="autores" class="form-control" rows="2" [(ngModel)]="autoresForm" name="autores"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Salvar Dados</button>
    </form>
</main>

// clientes/livros-next/pages/LivroDados.tsx
import React, { ChangeEvent, FormEvent, useState } from 'react';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Menu from '../componentes/Menu';
import { controleEditora } from './api/editoras';
import { ControleLivros } from '../classes/controle/ControleLivros';

interface Livro {
  codigo: string;
  titulo: string;
  resumo: string;
  autores: string[];
  codEditora: number;
}

const LivroDados = () => {
  const router = useRouter();
  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState(0);

  const controleLivros = new ControleLivros();

  const opcoes = controleEditora.getEditoras().map((editora) => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const tratarCombo = (e: ChangeEvent<HTMLSelectElement>) => {
    setCodEditora(Number(e.target.value));
  };

  const incluir = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const livro: Livro = {
      codigo: '',
      titulo,
      resumo,
      autores: autores.split('\n'),
      codEditora,
    };

    controleLivros.incluir(livro).then((sucesso) => {
      if (sucesso) router.push('/LivroLista');
    });
  };

  return (
    <div className={styles.containerDados}>
      <Head>
        <title>Loja Next</title>
        <meta name="description" content="Descrição da Loja Next" />
      </Head>

      <Menu />

      <main className={styles.mainDados}>
        <h1>Inclusão de Livro</h1>
        <form onSubmit={incluir} className={styles.form}>
          <input
            type="text"
            value={titulo}
            onChange={(e) => setTitulo(e.target.value)}
            placeholder="Título"
            className={styles.input}
          />
          <textarea
            value={resumo}
            onChange={(e) => setResumo(e.target.value)}
            placeholder="Resumo"
            className={styles.textarea}
          />
          <textarea
            value={autores}
            onChange={(e) => setAutores(e.target.value)}
            placeholder="Autores"
            className={styles.textarea}
          />
          <select value={codEditora} onChange={tratarCombo} className={styles.select}>
            {opcoes.map((option) => (
              <option key={option.value} value={option.value}>
                {option.text}
              </option>
            ))}
          </select>
          <button type="submit" className={styles.button}>
            Incluir
          </button>
        </form>
      </main>
    </div>
  );
};

export default LivroDados;
