// clientes/livros-react/src/LivroDados.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ControleLivros } from './controle/ControleLivros';
import  ControleEditora  from './controle/ControleEditora';

const LivroDados = () => {
  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState(1);

  const controleLivros = new ControleLivros();
  const controleEditora = new ControleEditora();

  const opcoes = controleEditora.getEditoras().map(editora => ({ value: editora.codEditora, text: editora.nome }));

  const navigate = useNavigate();

  const tratarCombo = (event) => {
    setCodEditora(Number(event.target.value));
  };

  const salvarDados = (event) => {
    event.preventDefault();
    const novoLivro = {
      codigo: '',
      titulo: titulo,
      resumo: resumo,
      autores: autores.split('\n'),
      codEditora: codEditora
    };
    controleLivros.incluir(novoLivro).then(() => {
      navigate('/');
    });
  };

  return (
    <div className="container mt-4">
      <h2>Dados do Livro</h2>
      <form onSubmit={salvarDados}>
        <div className="mb-3">
          <label htmlFor="titulo" className="form-label">Título</label>
          <input
            type="text"
            className="form-control"
            id="titulo"
            value={titulo}
            onChange={(e) => setTitulo(e.target.value)}
            placeholder="Titulo"
          />
        </div>
        <div className="mb-3">
          <label htmlFor="resumo" className="form-label">Resumo</label>
          <textarea
            className="form-control"
            id="resumo"
            value={resumo}
            onChange={(e) => setResumo(e.target.value)}
            rows="3"
          />
        </div>
        <div className="mb-3">
          <label htmlFor="editora" className="form-label">Editora</label>
          <select
            value={codEditora}
            onChange={tratarCombo}
            className='form-select'
          >
            {opcoes.map(opcao => <option key={opcao.value} value={opcao.value}>{opcao.text}</option>)}
          </select>
        </div>
        <div className="mb-3">
          <label htmlFor="autores" className="form-label">Autores (1 por linha)</label>
          <textarea
            className="form-control"
            id="autores"
            value={autores}
            onChange={(e) => setAutores(e.target.value)}
            rows="3"
          />
        </div>
        <button type="submit" className="btn btn-primary">Salvar Dados</button>
      </form>
    </div>
  );
}

export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {

  public livro: Livro = new Livro();
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('');
    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista');
    });
  }
}
<main class="container mt-4">
    <h1 class="mb-4">Dados do Livro</h1>

    <form (submit)="incluir()" ngNativeValidate>
        <div class="form-group">
            <label for="titulo">Título</label>
            <input type="text" id="titulo" class="form-control" [(ngModel)]="livro.titulo" name="titulo" required />
        </div>

        <div class="form-group">
            <label for="resumo">Resumo</label>
            <textarea id="resumo" class="form-control" rows="3" [(ngModel)]="livro.resumo" name="resumo"></textarea>
        </div>

        <div class="form-group">
            <label for="editora">Editora</label>
            <select id="editora" class="form-control" [(ngModel)]="livro.editora" name="editora" required>
                <option *ngFor="let editora of editoras" [value]="editora.codEditora">
                    {{ editora.nome }}
                </option>
            </select>
        </div>


        <div class="form-group">
            <label for="autores">Autores</label>
            <textarea id="autores" class="form-control" rows="2" [(ngModel)]="autoresForm" name="autores"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Salvar Dados</button>
    </form>
</main>
